### ISSUE TITLE
samples broken in readme.md

### ISSUE THREAD

**Issue by pelikhan** [sparkfun/pxt-weather-bit#10]
See https://makecode.microbit.org/pkg/sparkfun/pxt-weather-bit

Best way to edit the readme is to open the package from the local makecode editor and open the readme.md file (javascript -> explorer -> readme.md). You'll get a live preview from there.

**Comment by ADataDate** [comment]
fixed.

**Comment by pelikhan** [comment]
Second example...
```
basic.forever(Button.A, () => {
```

**Comment by ADataDate** [comment]
ok, it should work now.

**Comment by ADataDate** [comment]
ok now all the samples are broken.

**Comment by pelikhan** [comment]
fixed :)
