### ISSUE TITLE
Possible fix for "start weather monitoring" not working in "on start" block

### ISSUE THREAD

**Issue by wsnook** [sparkfun/pxt-weather-bit#13]
In the readme, you say:

> Set Up Function
> At the start of any program which will use the BME280 Sensor data (Pressure, Humidity, Altitude, Temperature) place the "Set up Weather Monitoring" in a "Forever" block. It is unknown at this time why this block will not work in the "On Start" block.

Is it possible that the "on start" block usually runs less than 2 ms after the BME280 gets power but the "forever" block usually starts after 2 ms? The BME280 datasheet lists tstartup (time to first communication after VDD and VDDIO at proper voltage) as 2ms (see section 1.1 General Electrical Specification, page 7 in the pdf I've got). Maybe I overlooked it, but I didn't notice anything in [weatherbit.ts:startWeatherMonitoring()](https://github.com/sparkfun/pxt-weather-bit/blob/308e020da7385ab291e41342c1cffd97ae7efa0e/weatherbit.ts#L271-L320) that looked like it would account for the start-up time.

I'm submitting this as an issue rather than pull request because I don't have a micro:bit or a weather:bit to test with, and I also am not set up to do PXT development. But, from reading your code, I'm wondering if it will magically start working if you do this:

![screen shot 2017-09-01 at 9 17 26 pm](https://user-images.githubusercontent.com/1828676/29992181-132d8d5e-8f5b-11e7-9bee-a03acd316b2d.png)

If so, then maybe you could fix the problem by adding a delay in `startWeatherMonitoring()` before trying to write to the I2C bus.

P.S. Your SEN-13676 BME280 breakout board is great.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. There was an issue with `Weather:bit` package but it has been fixed for months. For more information, check out the resolved issue => [https://github.com/sparkfun/pxt-weather-bit/issues/11](https://github.com/sparkfun/pxt-weather-bit/issues/11) . It did not appear to have anything to do with the initial start up. If you are still having issues, try re-adding the `Weatherbit` package and replacing the `Weatherbit` blocks in the code.

From what I understand, the example that is saved in your projects uses a snapshot of the package version. When the package is updated, the saved project still seems to use the previous version unless the package is re-added and the code blocks are replaced.
