### ISSUE TITLE
Use ``pxt-open-log`` library to handle openlog

### ISSUE THREAD

**Issue by pelikhan** [sparkfun/pxt-weather-bit#5]
Hide away OpenLog details by creating a ```sparkfun/pxt-open-log`` package that takes care of setting serial, etc... The package can be cross-referenced through the pxt.json file and will be usefull in other shields/projects.

**Comment by ADataDate** [comment]
we're thinking about it for future project releases but not at this time.

**Comment by pelikhan** [comment]
I could not find any documentation on the format supported by open-log

**Comment by ADataDate** [comment]
https://learn.sparkfun.com/tutorials/openlog-hookup-guide?_ga=2.4027952.1298171656.1496678841-1788647015.1453914745

this is currently the info we have for OpenLog. What info are you looking for specifically? What do you mean by format?

**Comment by pelikhan** [comment]
Does it just write all serial data to the sim? What does the resulting log look like?
