### ISSUE TITLE
Use ArrowNames for wind direction

### ISSUE THREAD

**Issue by pelikhan** [sparkfun/pxt-weather-bit#6]
We have an enum for cardinal direction, it also works with basic.showArray. You should use this instead of returning a string in https://github.com/sparkfun/pxt-weather-bit/blob/master/weatherbit.ts#L118.

https://github.com/Microsoft/pxt-microbit/blob/master/libs/core/icons.ts#L151

**Comment by ADataDate** [comment]
How does this work when the user wants to log the direction of the wind throughout the day?

**Comment by pelikhan** [comment]
He’ll log a number 😊

**Comment by ADataDate** [comment]
I'm going to hold off on doing this one.
