### ISSUE TITLE
Increment numRainDrops directly from pin event

### ISSUE THREAD

**Issue by pelikhan** [sparkfun/pxt-weather-bit#7]
In https://github.com/sparkfun/pxt-weather-bit/blob/master/weatherbit.ts#L95, I think you do not need to raise the event, just increment on the spot.

```
        // Watch pin 2 for a high pulse and send an event
        pins.onPulsed(DigitalPin.P2, PulseValue.High, () => {
            numRainDumps++
        })
```

**Comment by ADataDate** [comment]
I will do this once I get a new board. I had to give my last board away and I don't want to change code unless I can test it first.

**Comment by pelikhan** [comment]
For sure!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bboyho** [comment]
Hi,

Checking in with @ADataDate , it doesn't look like an "issue." From what I gathered, it seems like it is just another method to approach this problem and eventually it does the same thing.

I will be closing this issue. If there is a problem, we can always re-open this case. ;)
