### ISSUE TITLE
icon.png is too large

### ISSUE THREAD

**Issue by pelikhan** [sparkfun/pxt-weather-bit#9]
The icon will be shown in the project dialog. It should be as light as possible (kb) while retaining a good visual quality.

**Comment by ADataDate** [comment]
resized image to 1010 KB

**Comment by pelikhan** [comment]
100k max please

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ADataDate** [comment]
Ok got it down to 98K.

**Comment by ADataDate** [comment]
Does this image work?

**Comment by pelikhan** [comment]
Looks good.
